name: CI/CD Pipeline - Firefox Release
on:
  push:
    branches:
    - firefox-release
    - main
  workflow_dispatch:
jobs:
  publish-firefox-add-on:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the repository
      - name: move to the repo
        run: ls
      - name: Install node package
        run: npm install web-ext-submit
      - name: Upload and Release
        run: web-ext-submit --api-key=${{ secrets.FIREFOX_API_KEY }} --api-secret=${{ secrets.FIREFOX_API_SECRET }}
